<?php

namespace Trinos\Heroicons2\ViewModel;

use JetBrains\PhpStorm\Deprecated;

/**
 * Generated by generate-compat-functions.sh
 *
 * These methods only exist to provide backwards compatibility with the old Heroicons
 */
trait HeroiconsCompat
{

    #[Deprecated(
        reason: 'Replaced by adjustmentsVerticalHtml()',
        replacement: '%class%->adjustmentsVerticalHtml(%parametersList%)',
    )]
    public function adjustmentsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->adjustmentsVerticalHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by chatBubbleBottomCenterTextHtml()',
        replacement: '%class%->chatBubbleBottomCenterTextHtml(%parametersList%)',
    )]
    public function annotationHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->chatBubbleBottomCenterTextHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by archiveBoxHtml()',
        replacement: '%class%->archiveBoxHtml(%parametersList%)',
    )]
    public function archiveHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->archiveBoxHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowDownCircleHtml()',
        replacement: '%class%->arrowDownCircleHtml(%parametersList%)',
    )]
    public function arrowCircleDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowDownCircleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowLeftCircleHtml()',
        replacement: '%class%->arrowLeftCircleHtml(%parametersList%)',
    )]
    public function arrowCircleLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowLeftCircleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowRightCircleHtml()',
        replacement: '%class%->arrowRightCircleHtml(%parametersList%)',
    )]
    public function arrowCircleRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowRightCircleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowUpCircleHtml()',
        replacement: '%class%->arrowUpCircleHtml(%parametersList%)',
    )]
    public function arrowCircleUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowUpCircleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowLongDownHtml()',
        replacement: '%class%->arrowLongDownHtml(%parametersList%)',
    )]
    public function arrowNarrowDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowLongDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowLongLeftHtml()',
        replacement: '%class%->arrowLongLeftHtml(%parametersList%)',
    )]
    public function arrowNarrowLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowLongLeftHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowLongRightHtml()',
        replacement: '%class%->arrowLongRightHtml(%parametersList%)',
    )]
    public function arrowNarrowRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowLongRightHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowLongUpHtml()',
        replacement: '%class%->arrowLongUpHtml(%parametersList%)',
    )]
    public function arrowNarrowUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowLongUpHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowSmallLeftHtml()',
        replacement: '%class%->arrowSmallLeftHtml(%parametersList%)',
    )]
    public function arrowSmLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowSmallLeftHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowSmallRightHtml()',
        replacement: '%class%->arrowSmallRightHtml(%parametersList%)',
    )]
    public function arrowSmRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowSmallRightHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowSmallUpHtml()',
        replacement: '%class%->arrowSmallUpHtml(%parametersList%)',
    )]
    public function arrowSmUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowSmallUpHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowSmallDownHtml()',
        replacement: '%class%->arrowSmallDownHtml(%parametersList%)',
    )]
    public function arrowSmDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowSmallDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowsPointingOutHtml()',
        replacement: '%class%->arrowsPointingOutHtml(%parametersList%)',
    )]
    public function arrowsExpandHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowsPointingOutHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by checkBadgeHtml()',
        replacement: '%class%->checkBadgeHtml(%parametersList%)',
    )]
    public function badgeCheckHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->checkBadgeHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by noSymbolHtml()',
        replacement: '%class%->noSymbolHtml(%parametersList%)',
    )]
    public function banHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->noSymbolHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by bookmarkSquareHtml()',
        replacement: '%class%->bookmarkSquareHtml(%parametersList%)',
    )]
    public function bookmarkAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->bookmarkSquareHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by banknotesHtml()',
        replacement: '%class%->banknotesHtml(%parametersList%)',
    )]
    public function cashHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->banknotesHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by chartBarSquareHtml()',
        replacement: '%class%->chartBarSquareHtml(%parametersList%)',
    )]
    public function chartSquareBarHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->chartBarSquareHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by chatBubbleLeftRightHtml()',
        replacement: '%class%->chatBubbleLeftRightHtml(%parametersList%)',
    )]
    public function chatAlt2Html(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->chatBubbleLeftRightHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by chatBubbleLeftEllipsisHtml()',
        replacement: '%class%->chatBubbleLeftEllipsisHtml(%parametersList%)',
    )]
    public function chatAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->chatBubbleLeftEllipsisHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by chatBubbleOvalLeftEllipsisHtml()',
        replacement: '%class%->chatBubbleOvalLeftEllipsisHtml(%parametersList%)',
    )]
    public function chatHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->chatBubbleOvalLeftEllipsisHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by cpuChipHtml()',
        replacement: '%class%->cpuChipHtml(%parametersList%)',
    )]
    public function chipHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->cpuChipHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by clipboardDocumentCheckHtml()',
        replacement: '%class%->clipboardDocumentCheckHtml(%parametersList%)',
    )]
    public function clipboardCheckHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->clipboardDocumentCheckHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by clipboardDocumentHtml()',
        replacement: '%class%->clipboardDocumentHtml(%parametersList%)',
    )]
    public function clipboardCopyHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->clipboardDocumentHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by clipboardDocumentListHtml()',
        replacement: '%class%->clipboardDocumentListHtml(%parametersList%)',
    )]
    public function clipboardListHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->clipboardDocumentListHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by cloudArrowDownHtml()',
        replacement: '%class%->cloudArrowDownHtml(%parametersList%)',
    )]
    public function cloudDownloadHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->cloudArrowDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by cloudArrowUpHtml()',
        replacement: '%class%->cloudArrowUpHtml(%parametersList%)',
    )]
    public function cloudUploadHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->cloudArrowUpHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by codeBracketHtml()',
        replacement: '%class%->codeBracketHtml(%parametersList%)',
    )]
    public function codeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->codeBracketHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by rectangleStackHtml()',
        replacement: '%class%->rectangleStackHtml(%parametersList%)',
    )]
    public function collectionHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->rectangleStackHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by swatchHtml()',
        replacement: '%class%->swatchHtml(%parametersList%)',
    )]
    public function colorSwatchHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->swatchHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by cursorArrowRaysHtml()',
        replacement: '%class%->cursorArrowRaysHtml(%parametersList%)',
    )]
    public function cursorClickHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->cursorArrowRaysHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by circleStackHtml()',
        replacement: '%class%->circleStackHtml(%parametersList%)',
    )]
    public function databaseHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->circleStackHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by computerDesktopHtml()',
        replacement: '%class%->computerDesktopHtml(%parametersList%)',
    )]
    public function desktopComputerHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->computerDesktopHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by devicePhoneMobileHtml()',
        replacement: '%class%->devicePhoneMobileHtml(%parametersList%)',
    )]
    public function deviceMobileHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->devicePhoneMobileHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by documentPlusHtml()',
        replacement: '%class%->documentPlusHtml(%parametersList%)',
    )]
    public function documentAddHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->documentPlusHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by documentArrowDownHtml()',
        replacement: '%class%->documentArrowDownHtml(%parametersList%)',
    )]
    public function documentDownloadHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->documentArrowDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by documentMinusHtml()',
        replacement: '%class%->documentMinusHtml(%parametersList%)',
    )]
    public function documentRemoveHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->documentMinusHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by documentChartBarHtml()',
        replacement: '%class%->documentChartBarHtml(%parametersList%)',
    )]
    public function documentReportHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->documentChartBarHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by documentMagnifyingGlassHtml()',
        replacement: '%class%->documentMagnifyingGlassHtml(%parametersList%)',
    )]
    public function documentSearchHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->documentMagnifyingGlassHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by ellipsisHorizontalCircleHtml()',
        replacement: '%class%->ellipsisHorizontalCircleHtml(%parametersList%)',
    )]
    public function dotsCircleHorizontalHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->ellipsisHorizontalCircleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by ellipsisHorizontalHtml()',
        replacement: '%class%->ellipsisHorizontalHtml(%parametersList%)',
    )]
    public function dotsHorizontalHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->ellipsisHorizontalHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by ellipsisVerticalHtml()',
        replacement: '%class%->ellipsisVerticalHtml(%parametersList%)',
    )]
    public function dotsVerticalHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->ellipsisVerticalHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowDownTrayHtml()',
        replacement: '%class%->arrowDownTrayHtml(%parametersList%)',
    )]
    public function downloadHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowDownTrayHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by square2StackHtml()',
        replacement: '%class%->square2StackHtml(%parametersList%)',
    )]
    public function duplicateHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->square2StackHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by faceSmileHtml()',
        replacement: '%class%->faceSmileHtml(%parametersList%)',
    )]
    public function emojiHappyHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->faceSmileHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by faceFrownHtml()',
        replacement: '%class%->faceFrownHtml(%parametersList%)',
    )]
    public function emojiSadHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->faceFrownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowTopRightOnSquareHtml()',
        replacement: '%class%->arrowTopRightOnSquareHtml(%parametersList%)',
    )]
    public function externalLinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowTopRightOnSquareHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by exclamationTriangleHtml()',
        replacement: '%class%->exclamationTriangleHtml(%parametersList%)',
    )]
    public function exclamationHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->exclamationTriangleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by eyeSlashHtml()',
        replacement: '%class%->eyeSlashHtml(%parametersList%)',
    )]
    public function eyeOffHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->eyeSlashHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by forwardHtml()',
        replacement: '%class%->forwardHtml(%parametersList%)',
    )]
    public function fastForwardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->forwardHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by funnelHtml()',
        replacement: '%class%->funnelHtml(%parametersList%)',
    )]
    public function filterHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->funnelHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by folderPlusHtml()',
        replacement: '%class%->folderPlusHtml(%parametersList%)',
    )]
    public function folderAddHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->folderPlusHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by folderArrowDownHtml()',
        replacement: '%class%->folderArrowDownHtml(%parametersList%)',
    )]
    public function folderDownloadHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->folderArrowDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by folderMinusHtml()',
        replacement: '%class%->folderMinusHtml(%parametersList%)',
    )]
    public function folderRemoveHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->folderMinusHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by globeAmericasHtml()',
        replacement: '%class%->globeAmericasHtml(%parametersList%)',
    )]
    public function globeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->globeAmericasHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by handRaisedHtml()',
        replacement: '%class%->handRaisedHtml(%parametersList%)',
    )]
    public function handHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->handRaisedHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by inboxArrowDownHtml()',
        replacement: '%class%->inboxArrowDownHtml(%parametersList%)',
    )]
    public function inboxInHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->inboxArrowDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by buildingLibraryHtml()',
        replacement: '%class%->buildingLibraryHtml(%parametersList%)',
    )]
    public function libraryHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->buildingLibraryHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by boltHtml()',
        replacement: '%class%->boltHtml(%parametersList%)',
    )]
    public function lightningBoltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->boltHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by mapPinHtml()',
        replacement: '%class%->mapPinHtml(%parametersList%)',
    )]
    public function locationMarkerHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->mapPinHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowLeftOnRectangleHtml()',
        replacement: '%class%->arrowLeftOnRectangleHtml(%parametersList%)',
    )]
    public function loginHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowLeftOnRectangleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowRightOnRectangleHtml()',
        replacement: '%class%->arrowRightOnRectangleHtml(%parametersList%)',
    )]
    public function logoutHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowRightOnRectangleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by envelopeOpenHtml()',
        replacement: '%class%->envelopeOpenHtml(%parametersList%)',
    )]
    public function mailOpenHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->envelopeOpenHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by envelopeHtml()',
        replacement: '%class%->envelopeHtml(%parametersList%)',
    )]
    public function mailHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->envelopeHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by bars3CenterLeftHtml()',
        replacement: '%class%->bars3CenterLeftHtml(%parametersList%)',
    )]
    public function menuAlt1Html(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->bars3CenterLeftHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by bars3BottomLeftHtml()',
        replacement: '%class%->bars3BottomLeftHtml(%parametersList%)',
    )]
    public function menuAlt2Html(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->bars3BottomLeftHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by bars3BottomRightHtml()',
        replacement: '%class%->bars3BottomRightHtml(%parametersList%)',
    )]
    public function menuAlt3Html(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->bars3BottomRightHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by bars2Html()',
        replacement: '%class%->bars2Html(%parametersList%)',
    )]
    public function menuAlt4Html(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->bars2Html($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by bars3Html()',
        replacement: '%class%->bars3Html(%parametersList%)',
    )]
    public function menuHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->bars3Html($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by minusSmallHtml()',
        replacement: '%class%->minusSmallHtml(%parametersList%)',
    )]
    public function minusSmHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->minusSmallHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by musicalNoteHtml()',
        replacement: '%class%->musicalNoteHtml(%parametersList%)',
    )]
    public function musicNoteHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->musicalNoteHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by buildingOfficeHtml()',
        replacement: '%class%->buildingOfficeHtml(%parametersList%)',
    )]
    public function officeBuildingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->buildingOfficeHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by pencilSquareHtml()',
        replacement: '%class%->pencilSquareHtml(%parametersList%)',
    )]
    public function pencilAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->pencilSquareHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by phoneArrowDownLeftHtml()',
        replacement: '%class%->phoneArrowDownLeftHtml(%parametersList%)',
    )]
    public function phoneIncomingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->phoneArrowDownLeftHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by phoneXMarkHtml()',
        replacement: '%class%->phoneXMarkHtml(%parametersList%)',
    )]
    public function phoneMissedCallHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->phoneXMarkHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by phoneArrowUpRightHtml()',
        replacement: '%class%->phoneArrowUpRightHtml(%parametersList%)',
    )]
    public function phoneOutgoingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->phoneArrowUpRightHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by photoHtml()',
        replacement: '%class%->photoHtml(%parametersList%)',
    )]
    public function photographHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->photoHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by plusSmallHtml()',
        replacement: '%class%->plusSmallHtml(%parametersList%)',
    )]
    public function plusSmHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->plusSmallHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by puzzlePieceHtml()',
        replacement: '%class%->puzzlePieceHtml(%parametersList%)',
    )]
    public function puzzleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->puzzlePieceHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by qrCodeHtml()',
        replacement: '%class%->qrCodeHtml(%parametersList%)',
    )]
    public function qrcodeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->qrCodeHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by receiptPercentHtml()',
        replacement: '%class%->receiptPercentHtml(%parametersList%)',
    )]
    public function receiptTaxHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->receiptPercentHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowPathHtml()',
        replacement: '%class%->arrowPathHtml(%parametersList%)',
    )]
    public function refreshHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowPathHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowUturnLeftHtml()',
        replacement: '%class%->arrowUturnLeftHtml(%parametersList%)',
    )]
    public function replyHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowUturnLeftHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by backwardHtml()',
        replacement: '%class%->backwardHtml(%parametersList%)',
    )]
    public function rewindHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->backwardHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowDownOnSquareStackHtml()',
        replacement: '%class%->arrowDownOnSquareStackHtml(%parametersList%)',
    )]
    public function saveAsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowDownOnSquareStackHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowDownOnSquareHtml()',
        replacement: '%class%->arrowDownOnSquareHtml(%parametersList%)',
    )]
    public function saveHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowDownOnSquareHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by magnifyingGlassCircleHtml()',
        replacement: '%class%->magnifyingGlassCircleHtml(%parametersList%)',
    )]
    public function searchCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->magnifyingGlassCircleHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by magnifyingGlassHtml()',
        replacement: '%class%->magnifyingGlassHtml(%parametersList%)',
    )]
    public function searchHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->magnifyingGlassHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by chevronUpDownHtml()',
        replacement: '%class%->chevronUpDownHtml(%parametersList%)',
    )]
    public function selectorHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->chevronUpDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by barsArrowUpHtml()',
        replacement: '%class%->barsArrowUpHtml(%parametersList%)',
    )]
    public function sortAscendingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->barsArrowUpHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by barsArrowDownHtml()',
        replacement: '%class%->barsArrowDownHtml(%parametersList%)',
    )]
    public function sortDescendingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->barsArrowDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by megaphoneHtml()',
        replacement: '%class%->megaphoneHtml(%parametersList%)',
    )]
    public function speakerphoneHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->megaphoneHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by signalSlashHtml()',
        replacement: '%class%->signalSlashHtml(%parametersList%)',
    )]
    public function statusOfflineHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->signalSlashHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by signalHtml()',
        replacement: '%class%->signalHtml(%parametersList%)',
    )]
    public function statusOnlineHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->signalHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by lifebuoyHtml()',
        replacement: '%class%->lifebuoyHtml(%parametersList%)',
    )]
    public function supportHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->lifebuoyHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowsRightLeftHtml()',
        replacement: '%class%->arrowsRightLeftHtml(%parametersList%)',
    )]
    public function switchHorizontalHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowsRightLeftHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowsUpDownHtml()',
        replacement: '%class%->arrowsUpDownHtml(%parametersList%)',
    )]
    public function switchVerticalHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowsUpDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by tableCellsHtml()',
        replacement: '%class%->tableCellsHtml(%parametersList%)',
    )]
    public function tableHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->tableCellsHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by rectangleGroupHtml()',
        replacement: '%class%->rectangleGroupHtml(%parametersList%)',
    )]
    public function templateHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->rectangleGroupHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by commandLineHtml()',
        replacement: '%class%->commandLineHtml(%parametersList%)',
    )]
    public function terminalHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->commandLineHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by handThumbDownHtml()',
        replacement: '%class%->handThumbDownHtml(%parametersList%)',
    )]
    public function thumbDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->handThumbDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by handThumbUpHtml()',
        replacement: '%class%->handThumbUpHtml(%parametersList%)',
    )]
    public function thumbUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->handThumbUpHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by languageHtml()',
        replacement: '%class%->languageHtml(%parametersList%)',
    )]
    public function translateHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->languageHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowTrendingDownHtml()',
        replacement: '%class%->arrowTrendingDownHtml(%parametersList%)',
    )]
    public function trendingDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowTrendingDownHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowTrendingUpHtml()',
        replacement: '%class%->arrowTrendingUpHtml(%parametersList%)',
    )]
    public function trendingUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowTrendingUpHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by arrowUpTrayHtml()',
        replacement: '%class%->arrowUpTrayHtml(%parametersList%)',
    )]
    public function uploadHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->arrowUpTrayHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by userPlusHtml()',
        replacement: '%class%->userPlusHtml(%parametersList%)',
    )]
    public function userAddHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->userPlusHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by userMinusHtml()',
        replacement: '%class%->userMinusHtml(%parametersList%)',
    )]
    public function userRemoveHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->userMinusHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by viewColumnsHtml()',
        replacement: '%class%->viewColumnsHtml(%parametersList%)',
    )]
    public function viewBoardsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->viewColumnsHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by squaresPlusHtml()',
        replacement: '%class%->squaresPlusHtml(%parametersList%)',
    )]
    public function viewGridAddHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->squaresPlusHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by squares2x2Html()',
        replacement: '%class%->squares2x2Html(%parametersList%)',
    )]
    public function viewGridHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->squares2x2Html($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by bars4Html()',
        replacement: '%class%->bars4Html(%parametersList%)',
    )]
    public function viewListHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->bars4Html($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by speakerXMarkHtml()',
        replacement: '%class%->speakerXMarkHtml(%parametersList%)',
    )]
    public function volumeOffHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->speakerXMarkHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by speakerWaveHtml()',
        replacement: '%class%->speakerWaveHtml(%parametersList%)',
    )]
    public function volumeUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->speakerWaveHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by xMarkHtml()',
        replacement: '%class%->xMarkHtml(%parametersList%)',
    )]
    public function xHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->xMarkHtml($classnames, $width, $height, $attributes);
    }

    #[Deprecated(
        reason: 'Replaced by magnifyingGlassPlusHtml()',
        replacement: '%class%->magnifyingGlassPlusHtml(%parametersList%)',
    )]
    public function zoomInHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = []): string
    {
        return $this->magnifyingGlassPlusHtml($classnames, $width, $height, $attributes);
    }
}
